export const COMMENTS_REQUEST = 'COMMENTS_REQUEST'
export const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS'
export const COMMENTS_FAILURE = 'COMMENTS_FAILURE'

export const COMMENT_UPDATE_START = 'COMMENT_UPDATE_START'
export const COMMENT_UPDATE_REQUEST = 'COMMENT_UPDATE_REQUEST'
export const COMMENT_UPDATE_SUCCESS = 'COMMENT_UPDATE_SUCCESS'
export const COMMENT_UPDATE_FAILURE = 'COMMENT_UPDATE_FAILURE'
export const COMMENT_UPDATE_END = 'COMMENT_UPDATE_END'

export const COMMENT_CREATE_START = 'COMMENT_CREATE_START'
export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST'
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS'
export const COMMENT_CREATE_FAILURE = 'COMMENT_CREATE_FAILURE'
export const COMMENT_CREATE_END = 'COMMENT_CREATE_END'

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST'
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS'
export const COMMENT_DELETE_FAILURE = 'COMMENT_DELETE_FAILURE'

export const COMMENT_CHANGE_VOTE_REQUEST = 'COMMENT_CHANGE_VOTE_REQUEST'
export const COMMENT_CHANGE_VOTE_SUCCESS = 'COMMENT_CHANGE_VOTE_SUCCESS'
export const COMMENT_CHANGE_VOTE_FAILURE = 'COMMENT_CHANGE_VOTE_FAILURE'
