export const POSTS_REQUEST = 'POSTS_REQUEST'
export const POSTS_SUCCESS = 'POSTS_SUCCESS'
export const POSTS_FAILURE = 'POSTS_FAILURE'

export const POST_DETAILS_REQUEST = 'POST_DETAILS_REQUEST'
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS'
export const POST_DETAILS_FAILURE = 'POST_DETAILS_FAILURE'

export const POST_UPDATE_START = 'POST_UPDATE_START'
export const POST_UPDATE = 'POST_UPDATE'
export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST'
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS'
export const POST_UPDATE_FAILURE = 'POST_UPDATE_FAILURE'
export const POST_UPDATE_END = 'POST_UPDATE_END'

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST'
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS'
export const POST_CREATE_FAILURE = 'POST_CREATE_FAILURE'

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST'
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS'
export const POST_DELETE_FAILURE = 'POST_DELETE_FAILURE'

export const POST_CHANGE_VOTE_REQUEST = 'POST_CHANGE_VOTE_REQUEST'
export const POST_CHANGE_VOTE_SUCCESS = 'POST_CHANGE_VOTE_SUCCESS'
export const POST_CHANGE_VOTE_FAILURE = 'POST_CHANGE_VOTE_FAILURE'

export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER'
export const SORT_BY_TIME_ASC = 'SORT_BY_TIME_ASC'
export const SORT_BY_TIME_DESC = 'SORT_BY_TIME_DESC'
export const SORT_BY_VOTE_ASC = 'SORT_BY_VOTE_ASC'
export const SORT_BY_VOTE_DESC = 'SORT_BY_VOTE_DESC'
